### ISSUE TITLE
error: ‘for’ loop initial declarations are only allowed in C99 mode

### ISSUE THREAD

**Issue by xhylgogo** [fyne-io/fyne#1088]
### Describe the bug:
# fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.3/glfw
In file included from ../../fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.3/glfw/c_glfw_linbsd.go:14:0:
../../fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.3/glfw/glfw/src/x11_monitor.c: In function ‘getModeInfo’:
../../fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.3/glfw/glfw/src/x11_monitor.c:59:5: error: ‘for’ loop initial declarations are only allowed in C99 mode

### To Reproduce:
Steps to reproduce the behaviour:
1. Go to '1.14'

### Device (please complete the following information):
 - OS: [linux centos]
 - Version: [7.5]
 - Go version: [e.g. 1.14.0]
 - Fyne version: [e.g. 1.2.0 or git SHA]

**Comment by andydotxyz** [comment]
This is strange. I don't know much about Centos, can you provide some information about the `gcc` version and any development configuration you have set up?
Is the system completely up to date?

This may be vaguely related to an upstream note glfw/glfw#1560 but I'm not sure how we can set C99 mode from CGo... perhaps you could try adding `#cgo CFLAGS: -std=c99` into one of the `include "C"` headers and let us know if that helps.

**Comment by gael-lehech** [comment]
Had same issue on ubuntu 14.04 32 bits with go1.15.2 linux/386 and gcc 4.8.4, solved by adding `#cgo CFLAGS: -std=c99`
 at the beginning of fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.3/glfw/build.go

**Comment by andydotxyz** [comment]
It looks  like this has been resolved upstream, we will get the update over time

**Comment by pkk-code** [comment]
@andydotxyz May i know the timeframe, when this would be updated in fyne. I used fyne-cross to overcome this error but ran into this https://github.com/fyne-io/fyne-cross/issues/17.

**Comment by andydotxyz** [comment]
I thought it would have been in by now - do you still have the same error?

Can you confirm what version of `gcc` is installed?
It's likely that upgrading your centos would also fix the problem as I think it relates to an old `gcc` install.

**Comment by pkk-code** [comment]
I still get this error on CentOS7 

gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC)

**Comment by Jacalz** [comment]
I think that the gcc version most likely is too old here. It could be worth trying to compile the standard glfw source. If they don’t support this version of glibc + gcc, I don’t think there is much that we can do about it.

**Comment by Jacalz** [comment]
I'll close this. The mentioned fix has been merged upstream and has most likely trickled down to us now. If it has not, feel free to reopen. However, please keep in mind that gcc 4.8.5 is six years old at this time and has long since been out of support for both bugs and security fixes. I highly suggest upgrading to a newer gcc compiler and glibc for better security and performance.
