### ISSUE TITLE
Example in readme usually fails on debian buster with xmonad (0.14.2-3+b1)

### ISSUE THREAD

**Issue by apatil** [fyne-io/fyne#180]
The demo in the readme (https://github.com/fyne-io/fyne/blob/1b6d2d18120127086e6fb5691d813a9a0cf69b0a/README.md) sometimes works, but usually fails with

```
$ go run fyne.go
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  42 (X_SetInputFocus)
  Serial number of failed request:  176
  Current serial number in output stream:  178
```

**Comment by andydotxyz** [comment]
Blocked on #183

**Comment by andydotxyz** [comment]
This is very strange - do you have more information about when this occurs? Does the user interface fail to display or does it appear and trigger this error when you do something?

It seems we are triggering an error in X somehow which we will need to hunt down

**Comment by zenhack** [comment]
I am having the same issue with dwm. The app appears for a brief moment (just enough to be perceptible as a flicker) and then then exits, displaying the message above on the console.

Switching the window manager to "floating" mode seems to solve the problem, so presumably fyne doesn't like something about how tiling window managers try to lay them out.

**Comment by andydotxyz** [comment]
Ah! That’s an interesting point.

I wonder if it’s related to https://github.com/glfw/glfw/issues/789
That was fixed upstream in 3.2.1 which we may not have pulled in... (I think we use 3.2)

**Comment by andydotxyz** [comment]
It looks like Fyne is using 3.2.1 so that fix is in. Therefore we will have to investigate further.
I don't have xmonad installed - perhaps someone else can dig in? :)

**Comment by zenhack** [comment]
Hm, just sat down to try this again and I can't reproduce the problem :/

Quoting Andy Williams (2019-03-30 19:46:17)

**Comment by apatil** [comment]
Sorry for the late response. I still see the issue on master with https://github.com/fyne-io/fyne#code. However, the widget demo at https://github.com/fyne-io/fyne#widget-demo works reliably.

**Comment by andydotxyz** [comment]
With the basic code that is not working can you try "go build main.go && ./main" to see if it's a build issue somehow?

I cannot see what else is different as they use the same basic window load code.

**Comment by apatil** [comment]
Go build vs. go run doesn't make a difference.

**Comment by andydotxyz** [comment]
It may be a random question but does it behave any differently if you replace the widget.Label in the example with widget.Entry?

**Comment by apatil** [comment]
I replaced `widget.NewLabel("Hello Fyne!")` with `widget.NewEntry()`, and the same thing happened.

**Comment by andydotxyz** [comment]
Ok, sorry it was a long shot. If you are able to would it be possible to start from the fyne_demo code (cmd/fyne_demo/main.go) - which seems to work - and remove items from the main window until it stops working?

Hopefully it will show what something is causing them to behave differently?

**Comment by andydotxyz** [comment]
We have a lot of fixes relating window behaviour in 1.1 so this may now be resolved.
Can you please either test against develop branch or wait until 1.1 is released and check again?

**Comment by andydotxyz** [comment]
I can no longer replicate this
