### ISSUE TITLE
Layout issue after window has been moved to secondary display

### ISSUE THREAD

**Issue by SteffenMahler** [fyne-io/fyne#2704]
### Describe the bug:
My primary screen is a 24-inch 1080p screen and is controlled by my ThinkPad E480 (14inch, 1080p).

**Case 1**
If i start the sample application on my primary screen and move the window to the laptop screen, every thin is fyne ;-)
The detected scale is going from 1.0 (primary display) to 1.3152103 (laptop)
![image](https://user-images.githubusercontent.com/57138594/147097992-9928c68d-3ea0-4bae-84ee-c0fa16dc6691.png)

When I move the window back to my primary screen, layout issues occur.
![image](https://user-images.githubusercontent.com/57138594/147097935-fbb873e1-43ca-43b5-b95b-7ea768fbb34a.png)

**Case 2**
If I start the sample application from my secondary screen and move the window to the primary screen, this layout issue occurs immediately.

In both cases the layout will be fixed, after resizing the window!
![image](https://user-images.githubusercontent.com/57138594/147098508-c01c170b-9ca4-4bda-b85e-0218394df138.png)

### To Reproduce:
Steps to reproduce the behaviour:
1. Start the application.
2. Move window to secondary display.
3. Maybe move again to primary display.
4. See layout error.

### Example code:
```go
package main

import (
    "fyne.io/fyne/v2/app"
    "fyne.io/fyne/v2/container"
    "fyne.io/fyne/v2/theme"
    "fyne.io/fyne/v2/widget"
)

func main() {
    a := app.New()

    w := a.NewWindow("Fyne App")

    t := container.NewAppTabs(
        container.NewTabItem("Tab 1", widget.NewLabel("Content of Tab 1")),
        container.NewTabItem("Tab 2", widget.NewLabel("Content of Tab 2")),
    )

    w.SetContent(t)
    w.ShowAndRun()
}

```

This layout issue is also visible, for:
```go
...
t := container.NewVBox(
        widget.NewLabel("Label 1"),
        widget.NewLabel("Label 2"),
    )
```

### Device (please complete the following information):
 - **OS:** Linux
 - **Version:** Linux Mint 19 Tara
 - **Go version:** 1.17.5
 - **Fyne version:** v2.1.2

Can anyone confirm this issue?
Also, would it be a solution for you, if I provide a commit to make this auto-scaling optional?

**Comment by andydotxyz** [comment]
I think this relates to some window managers not allowing windows to resize (down?) whilst moving but I could be mistaken.
Perhaps this is a variant of that where the window does resize correctly but we do not redraw the window content?

**Comment by SteffenMahler** [comment]
@andydotxyz 
I would like to refer again to my last question. Is it an option, if I provide a pull request to make this auto-scaling optional?

**Comment by andydotxyz** [comment]
Sorry I missed that. Having auto-scaling be optional doesn't seem like the right solution.
We want to ensure that apps look the right size for every device, and that would break this.
It looks more like there is a bug in how the scaling works on your Mint system. We should fix the bug instead of removing the feature.

**Comment by SteffenMahler** [comment]
Hello Andy,

you're right. The automatic scaling should work as intended on all devices.

So I updated my Linux Mint to 20.3 (una) and the rescaling problem still occurs.

What do you think about the idea of being able to turn off rescaling when moving the app? On which other systems is this feature needed?

**Comment by Jacalz** [comment]
> What do you think about the idea of being able to turn off rescaling when moving the app?

I personally agree with the previous answer by Andy (https://github.com/fyne-io/fyne/issues/2704#issuecomment-1028405347) , on this topic. An option to turn it off is not the right solution.

**Comment by Jacalz** [comment]
We will update with information once there is something new to share. However, that video does not seem to show what original issue is talking about? It makes sense that the scaling on two differently sized monitors is different.

**Comment by SteffenMahler** [comment]
You are right. But this viedo will show it.

> It makes sense that the scaling on two differently sized monitors is different.
I have to ask why. The terminal window isn't resized. Not a single window is resized except for Fyne applications. Also, initial scaling factor for all applications (except fyne) is 1.0. The pixel density of the display, and this is the only difference between the two displays, does not affect other applications.

I like fyne.io a lot, but at the moment it makes no sense for me to use it if this problem is not solved.

**Comment by Jacalz** [comment]
That looks very bad. Thanks for sharing that video. The window size should not change like that.
I just tested moving windows back and forth between my 1080p and 1440p screens but can not replicate it. I guess it could be specific to when both screens have the same resolution but different sizes.

**Comment by SteffenMahler** [comment]
@Jacalz thank you for testing.

In fact, the screen of my laptop is smaller but has the same resolution.
Do you have an idea to solve this problem? I would contribute...

**Comment by andydotxyz** [comment]
When deciding how large a window should be we look at the OS scaling setting (but Linux doesn't have one) then we fall back to the DPI of the devices. Your screens having the same resolution but different sizes means that they have different DPIs. Therefore we will use a different number of pixels to display the same content. This is intended behaviour when no OS scale can be found. If you measure the windows you will see that they are the same size.

Window size is very complex but we aim for consistent font size across all devices - the baseline for mobile is clearly smaller as you hold it closer to your face. We assume that laptop and desktop screens are, for the majority, a similar distance from your face and so use the same target DPI.
Linux is "special" in this area because most other (X11) toolkits assume that the pixel is the most important measurement - which is what leads to unreadably small text on 4K until user intervention fixes some environment to account for it.

The (second) video that you have provided shows clearly what I had considered in my initial reply:

> I think this relates to some window managers not allowing windows to resize (down?) whilst moving but I could be mistaken.

The dragging of the window to a new screen will request a resize in your case. You can see that it works when scaling up, but not when scaling down. We issue the window resize but it is ignored.
If you could provide any information about the window manager and configuration that would be helpful, I am not familiar with Linux Mint specifics and it is not one of the variants we have tested.

> I like fyne.io a lot, but at the moment it makes no sense for me to use it if this problem is not solved.

I am sorry to hear this of course. We generally prioritise by severity or number of people experiencing the problem. If you feel we have not prioritised it high enough for you, please do consider supporting the project at the "bug fix" level and would get an expedite https://fyne.io/sponsor/.

**Comment by SteffenMahler** [comment]
Ok, I understand. I will have a look at https://github.com/linuxmint/muffin ...

**Comment by SteffenMahler** [comment]
I have an update on this issue. It's a timing problem.

The sleep of 400ms is realy long, but it solves this issue - on a realy dirty way. will investigate this further...

https://user-images.githubusercontent.com/57138594/207930019-cc65d4e2-2bc6-461f-b684-74e942617015.mp4

**Comment by SteffenMahler** [comment]
This is sad. The issue still exists, if I don't release the mouse button :-(

**Comment by andydotxyz** [comment]
Yup, the window manager is dis-allowing the window to become smaller until the mouse up event happens.
I honestly don't know what we can do about this. Perhaps you can request support or thoughts from the WM developers?

**Comment by andydotxyz** [comment]
There is now an environment variable users can set to turn off DPI detection
