### ISSUE TITLE
Is it possible to implement the right-click interface of the two-dimensional table?

### ISSUE THREAD

**Issue by sh1luo** [fyne-io/fyne#3910]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

no

### Is it possible to construct a solution with the existing API?

not supported now

### Describe the solution you'd like to see.

When I click the right mouse button on the table cell, I can trigger the method implemented by myself.

Such as,

```golang
func (b *contextTable) TappedSecondary(e *fyne.PointEvent) {
	//widget.ShowPopUpMenuAtPosition(b.menu, fyne.CurrentApp().Driver().CanvasForObject(b), e.AbsolutePosition)
	log.Println("right click！", time.Now(), "absolute:", e.AbsolutePosition, "position:", e.Position)
}
```

**Comment by andydotxyz** [comment]
The code you have pasted should work - what is not happening for you?

**Comment by sh1luo** [comment]
> The code you have pasted should work - what is not happening for you?

I pasted all code, which does not worked for me.

```golang
type contextTable struct {
	*widget.Table
}

func newContextTable(t *widget.Table) *contextTable {
	b := new(contextTable)
	b.Table = t

	b.ExtendBaseWidget(b)
	return b
}

func (b *contextTable) Tapped(e *fyne.PointEvent) {
	// widget.ShowPopUpMenuAtPosition(b.menu, fyne.CurrentApp().Driver().CanvasForObject(b), e.AbsolutePosition)
	log.Println("left click！", time.Now(), "absolute:", e.AbsolutePosition, "position:", e.Position)
}

func (b *contextTable) TappedSecondary(e *fyne.PointEvent) {
	//widget.ShowPopUpMenuAtPosition(b.menu, fyne.CurrentApp().Driver().CanvasForObject(b), e.AbsolutePosition)
	log.Println("right click！", time.Now(), "absolute:", e.AbsolutePosition, "position:", e.Position)
}

```

**Comment by sh1luo** [comment]
> > The code you have pasted should work - what is not happening for you?
> 
> I pasted all code, which does not work for me, including `Tapped` and `TappedSecondary`.
> 
> ```go
> type contextTable struct {
> 	*widget.Table
> }
> 
> func newContextTable(t *widget.Table) *contextTable {
> 	b := new(contextTable)
> 	b.Table = t
> 
> 	b.ExtendBaseWidget(b)
> 	return b
> }
> 
> func (b *contextTable) Tapped(e *fyne.PointEvent) {
> 	// widget.ShowPopUpMenuAtPosition(b.menu, fyne.CurrentApp().Driver().CanvasForObject(b), e.AbsolutePosition)
> 	log.Println("left click！", time.Now(), "absolute:", e.AbsolutePosition, "position:", e.Position)
> }
> 
> func (b *contextTable) TappedSecondary(e *fyne.PointEvent) {
> 	//widget.ShowPopUpMenuAtPosition(b.menu, fyne.CurrentApp().Driver().CanvasForObject(b), e.AbsolutePosition)
> 	log.Println("right click！", time.Now(), "absolute:", e.AbsolutePosition, "position:", e.Position)
> }
> ```

by the way, fyne version is v2.2.4, because does not support chinese `msyh.ttc` font type, i have to use the lower version. I am not sure that the higher version can solve this problem.

**Comment by andydotxyz** [comment]
The .ttc panic was fixed from 2.3.4 or earlier.
The .ttc font type has never been supported - it just didn't crash before!

**Comment by andydotxyz** [comment]
When I run your code and click / right click I get the following output:
```
2023/05/24 14:17:19 left click！ 2023-05-24 14:17:19.419109 +0100 BST m=+2.526086376 absolute: {19 25} position: {13 19}
2023/05/24 14:17:20 right click！ 2023-05-24 14:17:20.551917 +0100 BST m=+3.658885501 absolute: {19 25} position: {13 19}
```

**Comment by sh1luo** [comment]
> 

I just upgraded from v2.2.4 to v2.3.4, the program still panic, the error is as follows:

```cmd
2023/05/24 21:23:18 Fyne error:  font load error
2023/05/24 21:23:18   Cause: collections not allowed
2023/05/24 21:23:18   At: C:/Users/name/gopath/pkg/mod/fyne.io/fyne/v2@v2.3.4/internal/painter/font.go:150
```

But the exact same code can be loaded and display Chinese fonts in 2.2.4:

```golang
func init() {
	fontPaths, err := findfont.Find("msyh.ttc")
	if err != nil {
		log.Println("not found!")
		HmTTf = backup
		return
	}

	HmTTf, err = os.ReadFile(fontPaths)
	if err != nil {
		log.Println(err)
	}
}
```

**Comment by sh1luo** [comment]
> When I run your code and click / right click I get the following output:
> 
> ```
> 2023/05/24 14:17:19 left click！ 2023-05-24 14:17:19.419109 +0100 BST m=+2.526086376 absolute: {19 25} position: {13 19}
> 2023/05/24 14:17:20 right click！ 2023-05-24 14:17:20.551917 +0100 BST m=+3.658885501 absolute: {19 25} position: {13 19}
> ```

Can you show your full code why mine doesn't work. .

**Comment by andydotxyz** [comment]
> Can you show your full code why mine doesn't work. .

I just put your table into a window - nothing extra

**Comment by andydotxyz** [comment]
> But the exact same code can be loaded and display Chinese fonts in 2.2.4:

I can promise you that Fyne could not display the result of that load - we do not support .ttc fonts.

**Comment by andydotxyz** [comment]
My apologies, the fix is on develop only - it was resolved in https://github.com/fyne-io/fyne/pull/3654

**Comment by sh1luo** [comment]
![QQ截图20230524224337](https://github.com/fyne-io/fyne/assets/51157931/4065f8e4-89ec-4e54-81d5-1a251686f204)
> My apologies, the fix is on develop only - it was resolved in #3654

Thanks to the developers for efforts!

1. To be honest, although I don't know the reason, I did succeed in displaying Chinese in version 2.2.4 using `msyh.ttc`. But if I change to a higher version, an error will be reported. Therefore, I did not always upgrade to the latest version of fyne to experience the latest features, although I have been paying attention to the update of fyne:(((((( I am also looking forward to the new version to solve this problem.
2. My code can't trigger the right click button event, maybe my version is too low, I guess

**Comment by andydotxyz** [comment]
> 2\. My code can't trigger the right click button event, maybe my version is too low, I guess

The full code I had to write for your example to compile was:

```go
// Package main loads a very basic Hello World graphical application.
package main

import (
	"log"
	"time"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Hello")

	table := &widget.Table{
		Length: func() (int, int) {
			return 5, 5
		},
		CreateCell: func() fyne.CanvasObject {
			return widget.NewLabel("Hi")
		},
		UpdateCell: func(id widget.TableCellID, object fyne.CanvasObject) {}}
	w.SetContent(newContextTable(table))

	w.ShowAndRun()
}

type contextTable struct {
	*widget.Table
}

func newContextTable(t *widget.Table) *contextTable {
	b := new(contextTable)
	b.Table = t

	b.ExtendBaseWidget(b)
	return b
}

func (b *contextTable) Tapped(e *fyne.PointEvent) {
	// widget.ShowPopUpMenuAtPosition(b.menu, fyne.CurrentApp().Driver().CanvasForObject(b), e.AbsolutePosition)
	log.Println("left click！", time.Now(), "absolute:", e.AbsolutePosition, "position:", e.Position)
}

func (b *contextTable) TappedSecondary(e *fyne.PointEvent) {
	//widget.ShowPopUpMenuAtPosition(b.menu, fyne.CurrentApp().Driver().CanvasForObject(b), e.AbsolutePosition)
	log.Println("right click！", time.Now(), "absolute:", e.AbsolutePosition, "position:", e.Position)
}
```

I wonder if there is something complicated about how the table is implemented internally...
It works on `develop` branch.

However something that will always work, and is probably better anyway, is to add the callback on the items /inside/ your table - that way you know what cell was right clicked :)

**Comment by sh1luo** [comment]
> > 2. My code can't trigger the right click button event, maybe my version is too low, I guess
> 
> The full code I had to write for your example to compile was:
> 
> ```go
> // Package main loads a very basic Hello World graphical application.
> package main
> 
> import (
> 	"log"
> 	"time"
> 
> 	"fyne.io/fyne/v2"
> 	"fyne.io/fyne/v2/app"
> 	"fyne.io/fyne/v2/widget"
> )
> 
> func main() {
> 	a := app.New()
> 	w := a.NewWindow("Hello")
> 
> 	table := &widget.Table{
> 		Length: func() (int, int) {
> 			return 5, 5
> 		},
> 		CreateCell: func() fyne.CanvasObject {
> 			return widget.NewLabel("Hi")
> 		},
> 		UpdateCell: func(id widget.TableCellID, object fyne.CanvasObject) {}}
> 	w.SetContent(newContextTable(table))
> 
> 	w.ShowAndRun()
> }
> 
> type contextTable struct {
> 	*widget.Table
> }
> 
> func newContextTable(t *widget.Table) *contextTable {
> 	b := new(contextTable)
> 	b.Table = t
> 
> 	b.ExtendBaseWidget(b)
> 	return b
> }
> 
> func (b *contextTable) Tapped(e *fyne.PointEvent) {
> 	// widget.ShowPopUpMenuAtPosition(b.menu, fyne.CurrentApp().Driver().CanvasForObject(b), e.AbsolutePosition)
> 	log.Println("left click！", time.Now(), "absolute:", e.AbsolutePosition, "position:", e.Position)
> }
> 
> func (b *contextTable) TappedSecondary(e *fyne.PointEvent) {
> 	//widget.ShowPopUpMenuAtPosition(b.menu, fyne.CurrentApp().Driver().CanvasForObject(b), e.AbsolutePosition)
> 	log.Println("right click！", time.Now(), "absolute:", e.AbsolutePosition, "position:", e.Position)
> }
> ```
> 
> I wonder if there is something complicated about how the table is implemented internally... It works on `develop` branch.
> 
> However something that will always work, and is probably better anyway, is to add the callback on the items /inside/ your table - that way you know what cell was right clicked :)

Amazing, why it still doesn't work...it's wired
![111](https://github.com/fyne-io/fyne/assets/51157931/9294c0a1-bbff-4816-8394-2661432d48fc)

**Comment by sh1luo** [comment]
Excuse me, is there anyone else, why the same code doesn't work for me...it's so strange and amazing...

**Comment by matwachich** [comment]
Try not using a pointer to table in your extended type, but a table directly

**Comment by sh1luo** [comment]
> 

It still doesn't work for me
![ssss](https://github.com/fyne-io/fyne/assets/51157931/9bcd52c9-e492-4418-8b8a-078ec211e206)

**Comment by Jacalz** [comment]
I'd do it this way instead to make the `contextTable` be a table directly instead of passing in a pointer. This way the table exposes all its methods correctly:
```go
// Package main loads a very basic Hello World graphical application.
package main

import (
	"log"
	"time"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Hello")

	w.SetContent(
		newContextTable(
			func() (int, int) {
				return 5, 5
			},
			func() fyne.CanvasObject {
				return widget.NewLabel("Hi")
			},
			func(id widget.TableCellID, object fyne.CanvasObject) {},
		),
	)

	w.ShowAndRun()
}

type contextTable struct {
	widget.Table
}

func newContextTable(length func() (int, int), create func() fyne.CanvasObject, update func(id widget.TableCellID, object fyne.CanvasObject)) *contextTable {
	b := new(contextTable)
	b.ExtendBaseWidget(b)

	b.Length = length
	b.CreateCell = create
	b.UpdateCell = update
	return b
}

func (b *contextTable) Tapped(e *fyne.PointEvent) {
	// widget.ShowPopUpMenuAtPosition(b.menu, fyne.CurrentApp().Driver().CanvasForObject(b), e.AbsolutePosition)
	log.Println("left click！", time.Now(), "absolute:", e.AbsolutePosition, "position:", e.Position)
}

func (b *contextTable) TappedSecondary(e *fyne.PointEvent) {
	//widget.ShowPopUpMenuAtPosition(b.menu, fyne.CurrentApp().Driver().CanvasForObject(b), e.AbsolutePosition)
	log.Println("right click！", time.Now(), "absolute:", e.AbsolutePosition, "position:", e.Position)
}

```

**Comment by sh1luo** [comment]
> I'd do it this way instead to make the `contextTable` be a table directly instead of passing in a pointer. This way the table exposes all its methods correctly:
> 
> ```go
> // Package main loads a very basic Hello World graphical application.
> package main
> 
> import (
> 	"log"
> 	"time"
> 
> 	"fyne.io/fyne/v2"
> 	"fyne.io/fyne/v2/app"
> 	"fyne.io/fyne/v2/widget"
> )
> 
> func main() {
> 	a := app.New()
> 	w := a.NewWindow("Hello")
> 
> 	w.SetContent(
> 		newContextTable(
> 			func() (int, int) {
> 				return 5, 5
> 			},
> 			func() fyne.CanvasObject {
> 				return widget.NewLabel("Hi")
> 			},
> 			func(id widget.TableCellID, object fyne.CanvasObject) {},
> 		),
> 	)
> 
> 	w.ShowAndRun()
> }
> 
> type contextTable struct {
> 	widget.Table
> }
> 
> func newContextTable(length func() (int, int), create func() fyne.CanvasObject, update func(id widget.TableCellID, object fyne.CanvasObject)) *contextTable {
> 	b := new(contextTable)
> 	b.ExtendBaseWidget(b)
> 
> 	b.Length = length
> 	b.CreateCell = create
> 	b.UpdateCell = update
> 	return b
> }
> 
> func (b *contextTable) Tapped(e *fyne.PointEvent) {
> 	// widget.ShowPopUpMenuAtPosition(b.menu, fyne.CurrentApp().Driver().CanvasForObject(b), e.AbsolutePosition)
> 	log.Println("left click！", time.Now(), "absolute:", e.AbsolutePosition, "position:", e.Position)
> }
> 
> func (b *contextTable) TappedSecondary(e *fyne.PointEvent) {
> 	//widget.ShowPopUpMenuAtPosition(b.menu, fyne.CurrentApp().Driver().CanvasForObject(b), e.AbsolutePosition)
> 	log.Println("right click！", time.Now(), "absolute:", e.AbsolutePosition, "position:", e.Position)
> }
> ```

Maybe my computer crashed...it still does not worked for me...do you all work?!
![fuk](https://github.com/fyne-io/fyne/assets/51157931/cac3cf39-33f8-4527-83d1-56912ddffdf1)

**Comment by Jacalz** [comment]
That code does definitely work here and so did the old code. There might be something wrong with your terminal output. Add a `println` call and see if you get anything. This does not seem to be an issue in Fyne from what I can tell. 

Please note that for your code with checkboxes, the `widget.Check` that you are using is drawn on top so the tapped and tapped secondary methods are only actually pressed when you press outside of the check widget. You can see this by pressing in the white area on the edge of the cells. If you want individual cells to be tappable you should have the items within tappable and not the whole table.

**Comment by Jacalz** [comment]
Actually, I can replicate this not working using `v2.3.4`. It works fine on the `develop` branch.

**Comment by sh1luo** [comment]
> It works fine on the `develop` branch.

Maybe `develop` branch have any secrets:)...

**Comment by andydotxyz** [comment]
> I wonder if there is something complicated about how the table is implemented internally...
> It works on develop branch.
> 
> However something that will always work, and is probably better anyway, is to add the callback on the items /inside/ your table - that way you know what cell was right clicked :)

Indeed. My recommendation from above still holds - put click handlers on the cell widgets and it will always work. Plus you don't have to extend table to do this.

**Comment by huahua315148** [comment]
> > > The code you have pasted should work - what is not happening for you?
> > 
> > 
> > I pasted all code, which does not work for me, including `Tapped` and `TappedSecondary`.
> > ```go
> > type contextTable struct {
> > 	*widget.Table
> > }
> > 
> > func newContextTable(t *widget.Table) *contextTable {
> > 	b := new(contextTable)
> > 	b.Table = t
> > 
> > 	b.ExtendBaseWidget(b)
> > 	return b
> > }
> > 
> > func (b *contextTable) Tapped(e *fyne.PointEvent) {
> > 	// widget.ShowPopUpMenuAtPosition(b.menu, fyne.CurrentApp().Driver().CanvasForObject(b), e.AbsolutePosition)
> > 	log.Println("left click！", time.Now(), "absolute:", e.AbsolutePosition, "position:", e.Position)
> > }
> > 
> > func (b *contextTable) TappedSecondary(e *fyne.PointEvent) {
> > 	//widget.ShowPopUpMenuAtPosition(b.menu, fyne.CurrentApp().Driver().CanvasForObject(b), e.AbsolutePosition)
> > 	log.Println("right click！", time.Now(), "absolute:", e.AbsolutePosition, "position:", e.Position)
> > }
> > ```
> 
> by the way, fyne version is v2.2.4, because from v2.3.0 not supporting chinese `msyh.ttc` font type, which will panic. I have to use the lower version. I am not sure that the higher version can solve this problem.



> ![QQ截图20230524224337](https://private-user-images.githubusercontent.com/51157931/240642556-4065f8e4-89ec-4e54-81d5-1a251686f204.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0MDIwNTQsIm5iZiI6MTcwMjQwMTc1NCwicGF0aCI6Ii81MTE1NzkzMS8yNDA2NDI1NTYtNDA2NWY4ZTQtODllYy00ZTU0LTgxZDUtMWEyNTE2ODZmMjA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDE3MjIzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiODc2YjQ4NDU0MTM5Y2QwNDZmYzhmNTFkNjJhYzFjODQ0NTRkZTg0ODdiZWVjN2Q2MzEyNDBkNTBkNDk4YWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RRwF-iS_gVXmXT8vvjW1k2RVhhV9KJBuzM-LET_h-Pg)
> 
> > My apologies, the fix is on develop only - it was resolved in #3654
> 
> Thanks to the developers for efforts!
> 
> 1. To be honest, although I don't know the reason, I did succeed in displaying Chinese in version 2.2.4 using `msyh.ttc`. But if I change to a higher version, an error will be reported. Therefore, I did not always upgrade to the latest version of fyne to experience the latest features, although I have been paying attention to the update of fyne:(((((( I am also looking forward to the new version to solve this problem.
> 2. My code can't trigger the right click button event, maybe my version is too low, I guess

我能看看你使用新版本fyne解决中文乱码问题的代码吗
