### ISSUE TITLE
Negative SVF viewbox will not render

### ISSUE THREAD

**Issue by andydotxyz** [fyne-io/fyne#5313]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

An SVG with a negative viewbox, but nonetheless with valid content (all the coordinates within the viewfbox space) will not render. e.g. https://fonts.google.com/icons?selected=Material+Symbols+Outlined:favorite:FILL@0;wght@400;GRAD@0;opsz@24&icon.size=24&icon.color=%23e8eaed

### How to reproduce

Download icon and draw using `canvas.NewImageFromFile`

### Screenshots

nothing to see ;)

### Example code

`canvas.NewImageFromFile`

### Fyne version

v2.5.3/develop

### Go compiler version

1.21.4

### Operating system and version

all

### Additional Information

Probably been an issue for all versions

**Comment by andydotxyz** [comment]
Fixed on develop - if we have another 2.5.x I'll pick it over

**Comment by tinne26** [comment]
Since the oksvg fork doesn't accept issues, I'll just comment here:

This is a hacky fix to an issue that comes from oksvg itself, where this code:
```
func (s *SvgIcon) SetTarget(x, y, w, h float64) {
	scaleW := w / s.ViewBox.W
	scaleH := h / s.ViewBox.H
	s.Transform = rasterx.Identity.Translate(x-s.ViewBox.X, y-s.ViewBox.Y).Scale(scaleW, scaleH)
}
```
Should be doing this instead:
```
s.Transform = rasterx.Identity.Translate(x, y).Scale(scaleW, scaleH).Translate(-s.ViewBox.X, -s.ViewBox.Y)
```
Which is the correct "move to origin, then scale, then move to target", in post-multiply order.

The current fix is still wrong.

Here's a [demonstration of the three methods compared](https://gist.github.com/tinne26/cc33a5dcb397c27b62aaae458cb9ebac).

I could make a PR for fyne itself, but this should be fixed on oksvg.

**Comment by andydotxyz** [comment]
Please don't comment on closed issues. 

I don't know what you mean about upstream not accepting new issues, I just tapped https://github.com/srwiley/oksvg/issues/new and it worked great. They also accept pull requests.

If for some reason you have to work on the Fyne side please open a new issue or a new PR.

**Comment by tinne26** [comment]
The `fyne-io/oksvg` fork, not `srwiley/oksvg`, as that repository is not active ([as you yourself pointed out](https://github.com/srwiley/oksvg/pull/50#issuecomment-2766770167)). PR's are still allowed on `fyne-io/oksvg` though, so I followed up with that.

Sorry about that, I thought this was the most appropriate place to make the comment.

**Comment by andydotxyz** [comment]
> The fyne-io/oksvg fork, not srwiley/oksvg

My apologies, issues now enabled on our repository.

> Sorry about that, I thought this was the most appropriate place to make the comment.

An issue closed over a year ago is rarely the right place to comment ;). I see your pull request, we will get to reviewing that along with other items after the v2.8.0 release cycle completes at the end of the week.
